import { NextResponse } from "next/server";
import { createId, locales, type Locale } from "@eu-translation/shared";
import { extractTermsFromSource, uploadFileToVectorStore } from "@/lib/openai";
import { sourceTextFromUrl } from "@/lib/source";
import { DEFAULT_PROJECT_ID, store } from "@/lib/store";
import { getOpenAiKeyStatus } from "@/lib/settings";

export async function POST(request: Request) {
  try {
    const contentType = request.headers.get("content-type") ?? "";
    const sourceId = createId("source");
    let projectId = DEFAULT_PROJECT_ID;
    let sourceText = "";
    let sourceUrl: string | undefined;
    let localizedSources: Partial<Record<Locale, { sourceText: string; url: string }>> | undefined;
    let fileName: string | undefined;
    let openaiFileId: string | undefined;
    let vectorStoreId: string | undefined;

    if (contentType.includes("multipart/form-data")) {
      const formData = await request.formData();
      projectId = String(formData.get("projectId") || projectId);
      const file = formData.get("file");
      if (!(file instanceof File)) throw new Error("Missing PDF or Word file");
      fileName = file.name;
      if (!getOpenAiKeyStatus().configured) {
        throw new Error("OpenAI API key is required. Add it in Setting.");
      }
      if (process.env.OPENAI_VECTOR_STORE_ID) {
        const uploaded = await uploadFileToVectorStore(file);
        openaiFileId = uploaded.fileId;
        vectorStoreId = uploaded.vectorStoreId;
        sourceText = `Use File Search to extract terminology from uploaded document "${file.name}".`;
      } else {
        throw new Error("OPENAI_VECTOR_STORE_ID is required for PDF/Word terminology extraction.");
      }
    } else {
      const body = await request.json();
      projectId = String(body.projectId || projectId);
      sourceUrl = String(body.url || "");
      sourceText = sourceUrl ? await sourceTextFromUrl(sourceUrl) : String(body.text || "");
      if (body.syncLocalizedSources) {
        localizedSources = {};
        const localizedUrls = normalizeLocalizedUrls(body.localizedUrls);
        for (const locale of locales) {
          const localizedUrl = localizedUrls[locale];
          if (localizedUrl) {
            localizedSources[locale] = {
              sourceText: await sourceTextFromUrl(localizedUrl),
              url: localizedUrl
            };
          }
        }
      }
    }

    if (!sourceText.trim()) throw new Error("Source text is empty");

    const source = store.addSource({
      id: sourceId,
      projectId,
      type: fileName?.match(/\.docx?$/i) ? "word" : fileName ? "pdf" : "url",
      url: sourceUrl,
      fileName,
      openaiFileId,
      vectorStoreId,
      createdAt: new Date().toISOString()
    });
    const extracted = await extractTermsFromSource({
      localizedSources,
      projectId,
      sourceId,
      sourceText,
      sourceUrl,
      fileName,
      vectorStoreId
    });

    return NextResponse.json({
      source,
      terms: extracted,
      extractionMode: "ai",
      notice: localizedSources && Object.keys(localizedSources).length > 0
        ? syncNotice(Object.keys(localizedSources).length)
        : "AI generated translation. Click Save to add it to Library."
    });
  } catch (error) {
    return NextResponse.json({ error: error instanceof Error ? error.message : "Unknown error" }, { status: 400 });
  }
}

function syncNotice(localizedSourceCount: number): string {
  if (localizedSourceCount >= locales.length) {
    return "AI synced website translations. Click Save to add it to Library.";
  }
  return "AI synced website translations. Missing locale values were generated by AI. Click Save to add it to Library.";
}

function normalizeLocalizedUrls(value: unknown): Partial<Record<Locale, string>> {
  if (!value || typeof value !== "object") return {};
  const input = value as Record<string, unknown>;
  return Object.fromEntries(
    locales
      .map((locale) => {
        const url = String(input[locale] || "").trim();
        return url ? [locale, url] : undefined;
      })
      .filter((entry): entry is [Locale, string] => Boolean(entry))
  );
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const projectId = searchParams.get("projectId") || DEFAULT_PROJECT_ID;
  return NextResponse.json({ terms: store.listTerms(projectId) });
}
